name: "Renogy Bluetooth Monitor"
description: "Home Assistant add-on to monitor Renogy BMS devices via Bluetooth"
version: "1.0.0"
slug: "renogy-bt-ha"
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: "application"
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  devices:
    - address: ""
      alias: "renogy_battery"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  devices:
    - address: str
      alias: str
ports:
  1883/tcp: null
map:
  - config:rw
